### ISSUE TITLE
start is not checking already running instance

### ISSUE THREAD

**Issue by mareknovotny** [wildfly/wildfly-maven-plugin#130]
just a question, why start is not checking if the server is not already running?

I see that launching multiple times the same build will try to start multiple instances and obviously others instances in wrong not working state will keep in memory, but is effectively not started.

**Comment by mareknovotny** [comment]
Looking at https://github.com/wildfly/wildfly-maven-plugin/blob/master/plugin/src/main/java/org/wildfly/plugin/server/StartMojo.java#L284, it could be safe to add there something like
```java
if (ServerHelper.isStandaloneRunning(client)) {
    return;
}
```

**Comment by jamezp** [comment]
I actually think if a server is already running it should fail instead of just succeed. For example if the `start` goal is used to start a container before integration tests, but the user left a different test server running they may not want to deploy those integration tests on the currently running server.

We could test if the server is running and fail with an explicit message.

**Comment by mareknovotny** [comment]
That is true too, but  if it is the same server (location, profile etc)  you want to start? Anyway failure is a fix too ;)
