### ISSUE TITLE
Add Connection Timeout Parameter

### ISSUE THREAD

**Issue by eduardomoras** [wildfly/wildfly-maven-plugin#38]
Hello, I am using the plugin, but I have encountered problems of instability, caused by Connection Timeouts.

It is possible to include this parameter for all goals?

Windows 7
wildfly-8.2.0.Final
Java versions tested: 1.7, 1.7 64-bit, 64-bit 1.8
wildfly-maven-plugin 1.1.0.Alpha1

[ERROR] Failed to execute goal org.wildfly.plugins: wildfly-maven-plugin: 1.1.0.Alpha1: undeploy (default-cli) on project module.build: Could not run on goal undeploy \ module.build \ target \ checkout \ target \ module.war-1.0.war. Reason: I / O Error Could Not run operation '{
[ERROR] "operation" => "read-attribute"
[ERROR] "address" => []
[ERROR] "name" => "launch-type"
[ERROR]} ': java.net.ConnectException: WFLYPRT0023: Could not connect to http-remoting: //127.0.0.1: 9992. The connection timed out
[ERROR] -> [Help 1]

**Comment by gtstewart** [comment]
Check the port you using. The error message indicates you are using port 9992, the default port is 9990

Graham

**Comment by eduardomoras** [comment]
The problem is not the port as the port in use is actually 9992, because 9990 is in use by another application. When the port is wrong, the message is "Connection Refused", not "Connection Timeout".

In 50% of the connections, I have timeout errors, even using the jboss-cli.bat with the default timeout of 5 seconds. Setting the "connection-timeout" in JBoss-CLI connection for 15 seconds, the connection occurs in 100% of cases. The average time per connection in this environment, is 7 to 10 seconds.

For this reason, I request that I can configure in the plugin "wildfly-maven-plugin" the parameter connection-timeout.

Thanks,
Eduardo.

**Comment by miere** [comment]
Hi, I'm facing the same problem @eduardomoras has reported.
Is it planed to be fixed? Does it make sense to the wildfly team?

As we had serious deployments failing due to this timeout issue, I'm creating a local version of this plugin including the timeout parameter as an optional parameter in the ```AbstractServerConnection.java```. I'm keeping the same behavior defined at [deploy goal](http://docs.jboss.org/wildfly/plugins/maven/latest/deploy-mojo.html), providing a default value and a default property.

If you guys are interested on this correction, let me know and I'll send you a PR.

Miere

**Comment by jamezp** [comment]
Moved to https://github.com/wildfly/wildfly-maven-plugin/issues/38
